"""Live multi-category data source for the flip-or-flop scan.

Scrapes real, live Craigslist listings via Playwright — asking_price is the
actual price on the page, not fixture data. There's no ground-truth
"resale value" published anywhere for a listing, so estimated_resale_value
is generated by the LLM from the title/category, the same way a human
flipper sizes up a listing at a glance.

This is the real pipeline behind /api/scan now (see app.py). It does not
replace backend/data/playwright_loader.py — that fixture still backs the
frontend's own mock store and Person B's tests, which is a separate concern
from what data actually flows through the backend.
"""
import json
import logging
import os
import re
from pathlib import Path

from playwright.sync_api import sync_playwright

from backend.graph.llm import complete_with_retry

logger = logging.getLogger(__name__)

CRAIGSLIST_BASE = "https://sfbay.craigslist.org"

_DEFAULT_PLAYWRIGHT_CACHE = Path.home() / "Library/Caches/ms-playwright"


def _ensure_playwright_browsers_path() -> None:
    """Point Playwright at the real browser cache when Cursor's sandbox
    override points at an empty temp dir (the recurring scrape failure)."""
    current = os.environ.get("PLAYWRIGHT_BROWSERS_PATH", "")
    if current and Path(current).exists():
        return
    if _DEFAULT_PLAYWRIGHT_CACHE.exists():
        os.environ["PLAYWRIGHT_BROWSERS_PATH"] = str(_DEFAULT_PLAYWRIGHT_CACHE)


def _launch(p):
    """Launch Chromium, honoring demo-visibility env vars.

    PLAYWRIGHT_HEADED=1 shows the real browser window so a live demo can
    watch the scrape happen; PLAYWRIGHT_SLOW_MO=<ms> paces each action so
    it's watchable. Defaults stay headless/fast for reliability.
    """
    _ensure_playwright_browsers_path()
    headed = os.environ.get("PLAYWRIGHT_HEADED", "").strip().lower() in ("1", "true", "yes", "on")
    slow_mo = float(os.environ.get("PLAYWRIGHT_SLOW_MO", "0") or 0)
    return p.chromium.launch(headless=not headed, slow_mo=slow_mo)

# Verified live against Craigslist's current section codes (2026-06-21).
CATEGORY_CODES = {
    "furniture": "fua",
    "electronics": "ela",
    "tools": "tla",
    "collectibles": "cba",
    "sporting_goods": "sga",
    "instruments": "msa",
}
ITEMS_PER_CATEGORY = 5

# Rough miles from a fixed reference point (downtown Berkeley) so the "near
# you" framing has something real to show — not an actual geocoder.
_DISTANCE_LOOKUP = {
    "berkeley": 1.0, "oakland": 4.0, "emeryville": 3.0, "albany": 2.0,
    "richmond": 8.0, "san leandro": 9.0, "alameda": 7.0, "hayward": 14.0,
    "san francisco": 12.0, "russian hill": 13.0, "north bay / marin": 20.0,
    "san jose west": 45.0, "south bay": 45.0, "peninsula": 30.0,
}
_DEFAULT_DISTANCE_MILES = 15.0


def _parse_price(text: str) -> float | None:
    match = re.search(r"[\d,]+(\.\d+)?", text or "")
    if not match:
        return None
    return float(match.group(0).replace(",", ""))


def _estimate_distance(location: str) -> float:
    return _DISTANCE_LOOKUP.get((location or "").strip().lower(), _DEFAULT_DISTANCE_MILES)


def _scrape_category(page, category: str, code: str) -> list[dict]:
    page.goto(f"{CRAIGSLIST_BASE}/search/{code}", wait_until="domcontentloaded")
    page.wait_for_selector("li.cl-static-search-result", state="attached", timeout=15000)
    cards = page.query_selector_all("li.cl-static-search-result")

    listings = []
    for i, card in enumerate(cards):
        if len(listings) >= ITEMS_PER_CATEGORY:
            break
        title_el = card.query_selector(".title")
        price_el = card.query_selector(".price")
        loc_el = card.query_selector(".location")
        link_el = card.query_selector("a")
        if not title_el or not link_el:
            continue
        price = _parse_price(price_el.inner_text() if price_el else "")
        if price is None or price <= 0:
            continue
        location = loc_el.inner_text().strip() if loc_el else "Bay Area"
        listings.append({
            "id": f"live_{category}_{i}",
            "title": title_el.inner_text().strip(),
            "category": category,
            "asking_price": price,
            "location": location,
            "distance_miles": _estimate_distance(location),
            "url": link_el.get_attribute("href"),
            "image": "",
            "posted_at": None,
        })
    return listings


def _scrape_all_categories() -> list[dict]:
    listings = []
    with sync_playwright() as p:
        browser = _launch(p)
        page = browser.new_page()
        for category, code in CATEGORY_CODES.items():
            try:
                listings.extend(_scrape_category(page, category, code))
            except Exception as exc:
                logger.warning("scrape failed for %s (%s): %s", category, code, exc)
                continue
        browser.close()
    return listings


def _estimate_values(listings: list[dict]) -> dict[str, dict]:
    if not listings:
        return {}

    prompt = f"""You are an expert resale flipper estimating value for real, live marketplace listings.

For each listing below, only the title, category, and real asking price are known. Estimate:
- "condition": one of "like new", "good", "fair", "needs repair" — infer from the title's wording, default to "good" if there's no signal
- "estimated_resale_value": your best-guess realistic resale price in USD for this item in that condition, as a flipper pricing it to resell locally
- "description": one plausible sentence describing the item, based only on the title

Listings (JSON array):
{json.dumps([{"id": l["id"], "title": l["title"], "category": l["category"], "asking_price": l["asking_price"]} for l in listings])}

Return one entry per listing, same order, under "items"."""

    schema = {
        "type": "object",
        "properties": {
            "items": {
                "type": "array",
                "items": {
                    "type": "object",
                    "properties": {
                        "id": {"type": "string"},
                        "condition": {
                            "type": "string",
                            "enum": ["like new", "good", "fair", "needs repair"],
                        },
                        "estimated_resale_value": {"type": "number"},
                        "description": {"type": "string"},
                    },
                    "required": ["id", "condition", "estimated_resale_value", "description"],
                    "additionalProperties": False,
                },
            },
        },
        "required": ["items"],
        "additionalProperties": False,
    }
    # gemini-2.5-flash spends tokens on hidden reasoning before the visible
    # answer; 4096 was getting truncated for 30 listings.
    response = complete_with_retry(
        [{"role": "user", "content": prompt}],
        max_tokens=8192,
        schema_name="value_estimates",
        schema=schema,
    )
    parsed = json.loads(response.choices[0].message.content)["items"]
    return {item["id"]: item for item in parsed}


def load_listings() -> list[dict]:
    listings = _scrape_all_categories()
    estimates = _estimate_values(listings)

    result = []
    for item in listings:
        est = estimates.get(item["id"])
        if not est:
            continue
        result.append({
            **item,
            "condition": est.get("condition", "good"),
            "estimated_resale_value": est.get("estimated_resale_value"),
            "description": est.get("description"),
        })
    return result


def attach_images(items: list[dict]) -> list[dict]:
    """Fill in a real listing photo for items in the final queue.

    Craigslist's search-result cards carry no image at all (lazy-loaded,
    inaccessible without clicking through), so the only way to get a real
    photo is to visit each listing's own page. Doing that for all ~30
    scraped candidates would roughly double scan time, so this only runs
    on the post-filter queue — typically a handful of items — not the raw
    scrape output.
    """
    if not items:
        return items
    with sync_playwright() as p:
        browser = _launch(p)
        page = browser.new_page()
        for item in items:
            if not item.get("url"):
                continue
            try:
                page.goto(item["url"], wait_until="domcontentloaded", timeout=10000)
                img = page.query_selector(".swipe img, picture img, #thumbs img, img")
                if img:
                    item["image"] = img.get_attribute("src") or ""
            except Exception:
                continue
        browser.close()
    return items
